import { Sekuya } from "next/font/google";
import "./globals.css";

const fontsekuya = Sekuya({
  weight: "400",
});

export const metadata = {
  title: "BilalProtfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fontsekuya.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}