import Navbar from "./-components/reuseable.jsx/Navbar";
import "./globals.css";



export const metadata = {
  title: "BilalProtfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` h-full antialiased`} 
    suppressHydrationWarning 
    >
      <body className="min-h-full flex flex-col font-sekuya">
        {children}
      </body>
    </html>
  );
}